### ISSUE TITLE
Extending this to other ideas

### ISSUE THREAD

**Issue by trippyml** [vijishmadhavan/SkinDeep#2]
This is awesome, thank you for putting this together. If I wanted to extend this basic idea to other use cases (i.e. removing a logo from a car) how would I go about that? I can get both the "before" and "after" pictures of the car for training.

**Comment by vijishmadhavan** [comment]
This project might help, I will help if u get stuck.

**Comment by trippyml** [comment]
@vijishmadhavan Was there a link attached, or were you referring to the SkinDeep project?

**Comment by vijishmadhavan** [comment]
Yes SkinDeep project, Use ur dataset.
